:PACKAGE: ast

LICENSE = bsd,since=1985,author="Diomidis Spinellis,James A. Woods,Spencer Thomas,Joseph Orost"

CCFLAGS = $(CC.OPTIMIZE) $(CC.DLL)

compress plugin=codex :LIBRARY: compress.c

:TEST: codex

:: RELEASE
