/*
 * kpv delta/update library
 * retained for pax compatibility
 *
 * OBSOLETE: use vdelta
 */

:PACKAGE: ast

LICENSE = since=1989,author=kpv

odelta :LIBRARY: update.h suftree.h \
	delta.c mtchstring.c suftree.c update.c

$(INCLUDEDIR) :INSTALLPROTO: update.h
