:PACKAGE: ast:static

LICENSE		= since=1984,author='dgk+Pat Sullivan'
CCFLAGS		= $(CC.OPTIMIZE) $(CC.DLL)
VERSION		= 1.0

ESH		== 1
VSH		== 1
LDYNAMIC	== 1

edit $(VERSION) :LIBRARY: editlib.c vi.c emacs.c history.c edit.c +ldll

ie :: ie.sh

:: PROMO.mm RELEASE
