:PACKAGE: ast

LICENSE = since=1995,author=kpv

.SOURCE : vd01

vdelta 2.0 :LIBRARY: RELEASE vdelta.3 vdelta.h vdelhdr.h \
		vddelta.c vdio.c vdupdate.c vdsqueeze.c vdexpand.c \
		vdelta01.h vdelhdr01.h \
		vddelta01.c vdio01.c vdupdate01.c

$(INCLUDEDIR) :INSTALLPROTO: vdelta.h
