:PACKAGE: ast

LICENSE = since=1989,author=gsf

:ALL:

mamdag :: mamdag.sh

mamdot :: mamdot.sh

mamexec :: mamexec.sh

mamnew :: mamnew.c -lmam

mamold :: mamold.c -lmam

mamsh :: mamsh.sh

mamstate :: mamstate.c

:INSTALLDIR: mamtst

mamtst :: mamtst.c -lmam

:: RELEASE mamold.sh shmam.awk
