:PACKAGE: ast

LICENSE = since=1989,author=gsf

tw :: RELEASE PROMO.mm tw.c expr.c ftwlocal.c -lexpr -lsum

find :: find.c LICENSE=since=1989,author=gsf+dgk

locate :: locate.sh

updatedb :: updatedb.sh

:TEST: find tw

:: dag.tw dot.tw du.tw ls.tw
